name: Build Dropserver

on:
  push:
    branches: [ master ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Install Yarn
      run: npm install -g yarn

    - name: Frontend for ds-host
      run: yarn install && yarn run build 
      working-directory: frontend-ds-host

    - name: Frontend for ds-dev
      run: yarn install && yarn run build 
      working-directory: frontend-ds-dev

    - name: Uninstall Yarn
      if: always()
      run: npm uninstall -g yarn

    - name: Go Tests
      run: go test -timeout=60s -race ./...

    - name: Build ds-host
      run: go build -ldflags="-X main.cmd_version=`git describe --tags --dirty`" -o dist/bin/ds-host ./cmd/ds-host

    - name: Build ds-dev
      run: go build -o dist/bin/ds-dev ./cmd/ds-dev

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: true
        files: |
          dist/bin/ds-host
          dist/bin/ds-dev
