name: Build Dropserver

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_common:
    uses: teleclimber/DropServer/.github/workflows/build_common.yml@master

  build:
    needs: build_common
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Download frontend-ds-host
      uses: actions/download-artifact@v2
      with:
        name: frontend-ds-host
        path: frontend-ds-host/dist/

    - name: Download frontend-ds-dev
      uses: actions/download-artifact@v2
      with:
        name: frontend-ds-dev
        path: frontend-ds-dev/dist/

    # We don't test on build because for the time being some of our tests are flaky
    # Add tests here when we have that under control.

    - name: Build ds-host
      run: go build -ldflags="-X main.cmd_version=`git describe --tags --dirty`" -o dist/bin/ds-host ./cmd/ds-host

    - name: Build ds-dev
      run: go build -ldflags="-X main.cmd_version=`git describe --tags --dirty`" -o dist/bin/ds-dev ./cmd/ds-dev

    - name: Archive ds-host
      run: tar -czf ds-host-amd64-linux.tar.gz ds-host
      working-directory: dist/bin

    - name: Archive ds-dev
      run: tar -czf ds-dev-amd64-linux.tar.gz ds-dev
      working-directory: dist/bin

    - name: Release notes
      run: git log $(git rev-list --tags --max-count=1 --skip=1)..HEAD --oneline > dist/CHANGELOG.txt

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: dist/CHANGELOG.txt
        prerelease: false
        files: |
          dist/CHANGELOG.txt
          dist/bin/ds-host-amd64-linux.tar.gz
          dist/bin/ds-dev-amd64-linux.tar.gz
